package fr.guronzan.mediatheque.mappingclasses;

// Generated 27 août 2013 13:58:41 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private static final long serialVersionUID = 847598534421149408L;

	private Integer id;
	private String name;
	private String forName;
	private String password;
	private Date registrationDate;

	public User() {
	}

	public User(final String name, final String forName, final String password,
			final Date registrationDate) {
		this.name = name;
		this.forName = forName;
		this.password = password;
		this.registrationDate = registrationDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(final Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(final String name) {
		this.name = name;
	}

	public String getForName() {
		return this.forName;
	}

	public void setForName(final String forName) {
		this.forName = forName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(final String password) {
		this.password = password;
	}

	public Date getRegistrationDate() {
		return this.registrationDate;
	}

	public void setRegistrationDate(final Date registrationDate) {
		this.registrationDate = registrationDate;
	}

}
